name: flipzon
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.18.0
  shared_preferences: ^2.2.2
  flutter_automation: ^2.0.0
  google_mobile_ads: ^4.0.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/banners/
    - assets/macbook/
    - lib/device_data/iphone15Series.json
    - lib/device_data/iphone14Series.json
    - lib/device_data/iphone16Series.json
    - lib/device_data/ipadSeries.json
    - lib/device_data/mac/mabbookairSeries.json
